# If true, music will play automatically when the player joins the game.
# Allowed values: "true" or "false"
autoplay: true

# Allowed values: "order" or "random"
play-mode: random

delay-ticks: 20

created-resource-pack-name: "Radio-ResourcePack"